version: "3.8"

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: database

volumes:
  data: